#!/usr/bin/env node
// sync-cards.js — fetch card data from Firestore and regenerate src/data/cards.ts
//
// Usage:
//   npm run sync-cards
//   node scripts/sync-cards.js
//
// Reads the `cards` collection in Firestore (managed by herocards-cms),
// then overwrites src/data/cards.ts with the latest data.
// Run this any time you publish changes in the CMS and want to commit
// an updated cards.ts as a versioned backup + offline fallback.

const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore }        = require('firebase-admin/firestore');
const fs                      = require('fs');
const path                    = require('path');

// ── Firebase Admin init (uses Application Default Credentials) ─────────────
// Run once before using this script:
//   npm install -g firebase-tools
//   firebase login
//   gcloud auth application-default login
//
// OR set GOOGLE_APPLICATION_CREDENTIALS env var to a service account JSON.
let app;
try {
  app = initializeApp();
} catch (e) {
  // Already initialized (shouldn't happen in CLI usage)
  app = require('firebase-admin').app();
}

const db = getFirestore(app);
db.settings({ projectId: 'hero-cards-1f345' });

async function syncCards() {
  console.log('🔄 Fetching cards from Firestore...');
  const snap = await db.collection('cards').get();

  if (snap.empty) {
    console.error('❌ No cards found in Firestore. Seed the database first via the CMS.');
    process.exit(1);
  }

  const cards = snap.docs
    .map(d => ({ ...d.data(), id: Number(d.id) }))
    .sort((a, b) => a.id - b.id);

  console.log(`✅ Fetched ${cards.length} cards`);

  // ── Build TypeScript file ───────────────────────────────────────────────
  const lines = [
    '// AUTO-GENERATED by scripts/sync-cards.js — do not edit manually.',
    `// Last synced: ${new Date().toISOString()}`,
    '// Source of truth: Firestore `cards` collection (managed via herocards-cms)',
    '',
    'export interface Card {',
    '  id: number;',
    '  name: string;',
    '  type: string;',
    '  rarity: string;',
    '  power: number;',
    '  defense: number;',
    '  speed: number;',
    '  emoji: string;',
    '  desc: string;',
    '  pack: number;',
    '  alliance: string;',
    '  imageUrl?: string;  // Firebase Storage URL',
    '  ability?: string;   // Assigned via CMS',
    '}',
    '',
    'export const ALL_CARDS: Card[] = ' + JSON.stringify(cards, null, 2)
      .replace(/"([^"]+)":/g, '$1:')   // unquote keys
      .replace(/null,?\n/g, '')         // strip null fields
    + ';',
    '',
  ];

  const outPath = path.join(__dirname, '..', 'src', 'data', 'cards.ts');
  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
  console.log(`✅ Written to ${outPath}`);
  console.log('');
  console.log('Next steps:');
  console.log('  npx tsc --noEmit   # verify no TypeScript errors');
  console.log('  git diff src/data/cards.ts   # review changes');
  console.log('  git commit -am "Sync cards from Firestore"');
}

syncCards().catch(err => {
  console.error('❌ sync-cards failed:', err.message);
  process.exit(1);
});
